import { BadgeCheck, Check, ClipboardCheck, Clock3, ShieldCheck, Star } from "lucide-react";
import { SubpageShell } from "@/components/subpage-shell";

const factors = [{ title: "Identity & credentials", points: "40 points", detail: "Government-issued ID, official role, or organization registration reviewed privately." }, { title: "Update accuracy", points: "25 points", detail: "History of timely, source-backed information and corrections when needed." }, { title: "Delivery record", points: "25 points", detail: "On-time distribution reporting with reviewed receipts or field proof." }, { title: "Account history", points: "10 points", detail: "Time in good standing and completed verification refreshes." }];

export default function TrustPage() {
  return <SubpageShell eyebrow="TRUST & VERIFICATION" title="Know who’s behind every update." description="Bayanihan publishes only verified sources and aid recipients. Tap a badge to understand what was checked.">
    <article className="sub-card trust-profile"><div className="trust-profile-top"><span className="trust-avatar">MC</span><div><span className="subpage-eyebrow">PUBLIC TRUST PROFILE</span><h2>Marikina City DRRMO</h2><span className="verified-label government"><BadgeCheck size={14} /> Government/Agency-Verified</span></div><div className="trust-score"><b>96</b><span>TRUST SCORE</span></div></div><div className="trust-credentials"><span><ClipboardCheck size={15} /> Official local government disaster office</span><span><Check size={15} /> Office contact and authority confirmed</span><span><Clock3 size={15} /> Active on Bayanihan since 2024</span></div><p className="privacy-note"><ShieldCheck size={15} /> Personal IDs and private verification records are encrypted, reviewed by authorized staff, and never displayed here.</p></article>
    <div className="trust-section-title"><div><span className="subpage-eyebrow">HOW IT’S CALCULATED</span><h2>A score you can understand.</h2></div><span className="score-note"><Star size={14} /> Maximum 100 points</span></div>
    <div className="factor-list">{factors.map((factor, index) => <article className="sub-card trust-factor" key={factor.title}><span className="factor-number">0{index + 1}</span><div><b>{factor.title}</b><small>{factor.detail}</small></div><span className="factor-points">{factor.points}</span></article>)}</div>
    <section className="verification-levels"><h3>Verification levels</h3><div><span className="level-mark basic">1</span><p><b>ID-Verified</b><small>Identity checked privately by the verification team.</small></p></div><div><span className="level-mark org">2</span><p><b>Organization-Verified</b><small>Registration, leadership, and relief channel validated.</small></p></div><div><span className="level-mark gov">3</span><p><b>Government/Agency-Verified</b><small>Official authority confirmed through an agency source.</small></p></div></section>
  </SubpageShell>;
}
